language: python

os:
  - linux
  # - osx

python:
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
  - "nightly"

env:
  - OMP_NUM_THREADS=2

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc-multilib
  - pip install codecov

install:
  - pip install -r requirements.txt -vvv
  - pip install -e . -vvv

script:
  - python -m pytest -vv --benchmark-skip  # Test against installed code

after_success:
  # Uninstall to test coverage against sources
  - find . -type f -name "*.so" | xargs rm && find . -type f -name "*.c" | xargs rm
  - pip uninstall kerrpy_cython -y
  - python setup_test.py develop

  - pytest --cov --benchmark-skip

  - codecov
